### ISSUE TITLE
Footer Reddit icon

### ISSUE THREAD

**Issue by GhostTheSlayer** [Saborknight/7thaa-website#1]
Since we don't have a FB page I changed it to Reddit, so someone needs to change the icon xD

**Comment by Saborknight** [comment]
Gotcha, I'll do that tonight

**Comment by TheNightstalk3r** [comment]
Ford you think having a Facebook page would be useful?

**Comment by Saborknight** [comment]
@TheNightstalk3r out of context for this Issue. But by all means, make a new one or ask this on Discord, for the sake of keeping things focused.

**Comment by GhostTheSlayer** [comment]
I don't really think a Facebook page would be much of use since we have reddit and stuff.

**Comment by Saborknight** [comment]
Completed in last mentioned commit.
