### ISSUE TITLE
Add colour for mobile top bars and address bars which are part of the native browser UIs

### ISSUE THREAD

**Issue by Saborknight** [Saborknight/7thaa-website#6]
Using: http://stackoverflow.com/questions/26960703/how-to-change-the-color-of-header-bar-and-address-bar-in-newest-android-chrome-v

**Comment by GhostTheSlayer** [comment]
[Commit](https://github.com/Saborknight/7thaa-website/commit/488e9e92a62d763d279993d3a44e67fa0a83c8f6)
-Changed the icon to the 7AA one
-Color for mobile tab*
